# Generated by Django 5.2.10 on 2026-01-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invite_code',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True),
        ),
    ]
