# Generated by Django 5.2.10 on 2026-01-22 18:54

import django.db.models.deletion
from django.db import migrations, models


def migrate_partners(apps, schema_editor):
    Profile = apps.get_model('core', 'Profile')
    UserPartnerMappings = apps.get_model('core', 'UserPartnerMappings')
    for profile in Profile.objects.filter(partner__isnull=False):
        partner = profile.partner
        # Create mappings if not exist
        if not UserPartnerMappings.objects.filter(user=profile, partner=partner).exists():
            UserPartnerMappings.objects.create(user=profile, partner=partner, is_active=True)
        if not UserPartnerMappings.objects.filter(user=partner, partner=profile).exists():
            UserPartnerMappings.objects.create(user=partner, partner=profile, is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_invite_code_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPartnerMappings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings_as_partner', to='core.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings_as_user', to='core.profile')),
            ],
        ),
        migrations.RunPython(migrate_partners, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='profile',
            name='partner',
        ),
    ]
